name: Release

'on':
  push:
    tags:
      - 'v[0-9]+.[0-9]+.[0-9]+f'

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source
        uses: actions/checkout@v4

      - name: Setup golang
        uses: actions/setup-go@v5
        with:
          go-version: '^1.21.0'

      - name: Setup nodejs
        uses: actions/setup-node@v4
        with:
          node-version: '16'
          cache: 'npm'
          cache-dependency-path: web/package-lock.json

      - name: Install go-task
        run: |
          go install github.com/go-task/task/v3/cmd/task@latest

      - name: Install rpm
        run: |
          sudo apt update && sudo apt-get install rpm

      - name: Install deps
        run: |
          task deps

      - name: Reset repo
        run: |
          git reset --hard

      - name: Run release
        run: |
          GITHUB_TOKEN=${{ secrets.GITHUB_TOKEN }} task release:prod